// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsQuZCwMGHXUvKBWAlQcL4gO6ikmzBx0',
    appId: '1:397504970927:web:fa2d96815055c91053145a',
    messagingSenderId: '397504970927',
    projectId: 'todoapp-e27a8',
    authDomain: 'todoapp-e27a8.firebaseapp.com',
    storageBucket: 'todoapp-e27a8.appspot.com',
    measurementId: 'G-D0705KE5SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4qZzLSQmRaDdLF2l9SeTkHRf-Z7rraU',
    appId: '1:397504970927:android:b6ba373d3acd7e5b53145a',
    messagingSenderId: '397504970927',
    projectId: 'todoapp-e27a8',
    storageBucket: 'todoapp-e27a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9q0V8VaLKFjIc0Mrg9UMHpYflpTNEqA',
    appId: '1:397504970927:ios:1e149e0d2647c79e53145a',
    messagingSenderId: '397504970927',
    projectId: 'todoapp-e27a8',
    storageBucket: 'todoapp-e27a8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB9q0V8VaLKFjIc0Mrg9UMHpYflpTNEqA',
    appId: '1:397504970927:ios:f0e753761162c72a53145a',
    messagingSenderId: '397504970927',
    projectId: 'todoapp-e27a8',
    storageBucket: 'todoapp-e27a8.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
